import { TiersClient, TiersFournisseur, TiersCommercial, TiersProspect, Tier } from "@/types/tiers";

export const MOCK_CLIENTS: TiersClient[] = [
    {
        id: "CLI000425",
        type: "client",
        active: true,
        name: "ABBA ABAKAR",
        code: "CLI000425",
        pays: 'CMR',
        contact: "Contact Divers",
        formeJuridique: "Individuel",
        familleClient: "Grossiste",
        segment: 'ENTREPRISE',
        estAssujettiTVA: false,
        pricingCategory: { detail: true, demisGros: true, gros: true, superGros: true },
        address: "Douala, Cameroun",
        city: "Douala",
        postalCode: "",
        phoneNumber: "691551643",
        email: "",
        fax: "",
        website: "",
        plafondCredit: 500000,
        creditInfo: { activé: true, copiesFacture: 0, tauxRemise: 0 },
        financial: { solde: 0, modesPaiementAutorises: [], devise: 'XAF' },
        notes: "",
        balanceStatusData: [
            { magasin: "SURFACE VENTE ETOUDI", etat: "Facturé", blNo: "114MSVET20CP000000", livreLe: "08/01/2020", reglement: "par Compte", montantTTC: 360180 },
        ],
        paymentMethodsData: [
            { code: "CP", libelle: "par Compte", autorise: true },
            { code: "CC", libelle: "par Chèque", autorise: false },
            { code: "CE", libelle: "par Espèces", autorise: false },
        ],
        actions: [
            {
                id: "ACT-001",
                title: "Relance Facture Janvier",
                type: "RELANCE_PAIEMENT",
                object: "Facture non payée depuis 30 jours",
                followedBy: "1",
                notificationMethod: "EMAIL",
                date: new Date(new Date().setDate(new Date().getDate() + 2)),
                content: "Bonjour, sauf erreur de notre part...",
                effect: "IMMEDIATE",
                status: "PENDING",
                createdAt: new Date()
            }
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "CLI000426",
        type: "client",
        active: true,
        name: "SUPER MARCHÉ DOMINO",
        code: "CLI000426",
        pays: "CMR",
        contact: "M. TCHAPTCHET",
        formeJuridique: "SARL",
        familleClient: "Détaillant",
        segment: "REVENDEUR",
        pricingCategory: { detail: true, demisGros: false, gros: false, superGros: false },
        address: "Akwa, Douala",
        city: "Douala",
        postalCode: "BP 000",
        phoneNumber: "699000000",
        email: "contact@domino.cm",
        plafondCredit: 1000000,
        financial: { solde: 150000, modesPaiementAutorises: [], devise: 'XAF' },
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "CLI000427",
        type: "client",
        active: false,
        name: "LIBRAIRIE CENTRALE",
        code: "CLI000427",
        pays: "CMR",
        contact: "Mme FOUDA",
        formeJuridique: "SA",
        familleClient: "Détaillant",
        segment: "PARTICULIER",
        address: "Yaoundé Centre",
        city: "Yaoundé",
        postalCode: "BP 145",
        phoneNumber: "677123456",
        email: "librairie@centrale.cm",
        plafondCredit: 200000,
        financial: { solde: 0, modesPaiementAutorises: [], devise: 'XAF' },
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];

export const MOCK_FOURNISSEURS: TiersFournisseur[] = [
    {
        id: "FOU000100",
        type: "fournisseur",
        active: true,
        name: "GROSSISTE KADJI",
        codeFournisseur: "FOU000100",
        pays: "CMR",
        contact: "Service Commercial",
        formeJuridique: "SA",
        familleFournisseur: "Boissons",
        address: "Zone Industrielle Bassa",
        city: "Douala",
        postalCode: "BP 456",
        phoneNumber: "677000000",
        email: "commandes@kadji.cm",
        financial: { solde: 0, modesPaiementAutorises: [], devise: 'XAF' },
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "FOU000101",
        type: "fournisseur",
        active: true,
        name: "SABC - BRASSERIES",
        code: "FOU000101",
        pays: "CMR",
        contact: "Direction Commerciale",
        formeJuridique: "SA",
        familleFournisseur: "Boissons",
        modePaiement: "VIREMENT",
        address: "Bassa, Douala",
        city: "Douala",
        postalCode: "BP 900",
        phoneNumber: "233400000",
        email: "commercial@sabc.cm",
        financial: { solde: 0, modesPaiementAutorises: [], devise: 'XAF' },
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];

export const MOCK_COMMERCIAUX: TiersCommercial[] = [
    {
        id: "COM001",
        type: "commercial",
        active: true,
        name: "JEAN-PAUL TCHOUA",
        code: "COM001",
        matricule: "M-2024-001",
        contact: "Jean-Paul",
        email: "jp.tchoua@comops.com",
        phoneNumber: "699998877",
        address: "Akwa",
        city: "Douala",
        postalCode: "BP 000",
        commission: 5.0,
        typeCommercial: "INTERNE",
        zonesCouvertes: "OUEST",
        clients: ["CLI000425"],
        affaires: [
            { id: "AFF1", titre: "Contrat Grossiste K", montant: 5000000, status: "gagnée", date: new Date("2024-01-15") }
        ],
        paiements: [
            { id: 'PAY-01', date: new Date('2024-01-30'), montant: 5000, reference: 'VIR-001', statut: 'payé' }
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "COM002",
        type: "commercial",
        active: true,
        name: "MARIE NGUYEN",
        code: "COM002",
        matricule: "M-2024-002",
        contact: "Marie",
        email: "marie.n@comops.com",
        phoneNumber: "655443322",
        address: "Bastos",
        city: "Yaoundé",
        postalCode: "BP 101",
        commission: 7.0,
        typeCommercial: "INDEPENDANT",
        zonesCouvertes: "CENTRE",
        clients: ["CLI000426"],
        affaires: [
            { id: "AFF2", titre: "Appel d'offre Ministère", montant: 12000000, status: "en_cours", date: new Date() }
        ],
        paiements: [],
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];

export const MOCK_PROSPECTS: TiersProspect[] = [
    {
        id: "PRO001",
        type: "prospect",
        active: true,
        name: "PHARMACIE DE LA CÔTE",
        code: "PRO001",
        contact: "Dr. NGO",
        email: "pharma.cote@gmail.com",
        phoneNumber: "677112233",
        address: "Bonanjo",
        city: "Douala",
        postalCode: "BP 900",
        potentiel: "ELEVE",
        sourceProspect: "RECOMMANDATION",
        probabilite: 70,
        createdAt: new Date(),
        updatedAt: new Date(),
        notes: "Intéressé par le module stock"
    },
    {
        id: "PRO002",
        type: "prospect",
        active: true,
        name: "CLINIQUE DE L'ESPOIR",
        code: "PRO002",
        contact: "Dr. KOUAM",
        email: "contact@clinique-espoir.cm",
        phoneNumber: "699887766",
        address: "Biyem-Assi",
        city: "Yaoundé",
        postalCode: "BP 300",
        potentiel: "MOYEN",
        sourceProspect: "SITE_WEB",
        probabilite: 40,
        createdAt: new Date(),
        updatedAt: new Date(),
        notes: "A relancer semaine prochaine"
    },
    {
        id: "PRO003",
        type: "prospect",
        active: true,
        name: "BOUTIQUE MAMA SARA",
        code: "PRO003",
        contact: "Mme Sara",
        email: "",
        phoneNumber: "655001122",
        address: "Marché Central",
        city: "Douala",
        postalCode: "",
        potentiel: "FAIBLE",
        sourceProspect: "SALON",
        probabilite: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
        notes: "Petit budget, à voir"
    }
];

export const MOCK_TIERS: Tier[] = [
    ...MOCK_CLIENTS,
    ...MOCK_FOURNISSEURS,
    ...MOCK_COMMERCIAUX,
    ...MOCK_PROSPECTS
];
