import { TiersClient, TiersFournisseur, TiersCommercial, TiersProspect, Tier } from "@/types/tiers";

export const MOCK_CLIENTS: TiersClient[] = [
    {
        id: "CLI000425",
        type: "client",
        active: true,
        name: "ABBA ABAKAR",
        code: "CLI000425",
        pays: 'CMR',
        contact: "Contact Divers",
        formeJuridique: "Individuel",
        familleClient: "Grossiste",
        segment: 'ENTREPRISE',
        estAssujettiTVA: false,
        pricingCategory: { detail: true, demisGros: true, gros: true, superGros: true },
        modesPaiementClient: ['PAR_COMPTE', 'ESPECES'],
        categoriesVente: ['GROS', 'SUPER_GROS'],
        address: "Douala, Cameroun",
        city: "Douala",
        postalCode: "",
        phoneNumber: "691551643",
        email: "abba.abakar@gmail.com",
        fax: "",
        website: "",
        plafondCredit: 500000,
        creditInfo: { activé: true, copiesFacture: 0, tauxRemise: 5 },
        financial: { solde: 0, modesPaiementAutorises: [], devise: 'XAF' },
        notes: "Client fidèle depuis 2018.",
        compteComptable: "411-CLI425",
        registreCommerce: "RC/DLA/2015/B/1234",
        numeroFiscal: "M123456789A",
        factures: [
            {
                id: "FAC-001",
                numero: "FAC-2024-001",
                date: new Date("2024-01-08"),
                montantHT: 300000,
                montantTTC: 354000,
                statut: "payée",
                echeance: new Date("2024-02-08"),
            },
            {
                id: "FAC-002",
                numero: "FAC-2024-015",
                date: new Date("2024-03-15"),
                montantHT: 500000,
                montantTTC: 590000,
                statut: "en retard",
                echeance: new Date("2024-04-15"),
                actionSuivi: { type: "RELANCE_PAIEMENT", date: new Date("2024-04-20"), note: "Relance par email", statut: "DONE" },
            },
            {
                id: "FAC-003",
                numero: "FAC-2024-042",
                date: new Date("2024-06-01"),
                montantHT: 120000,
                montantTTC: 141600,
                statut: "envoée",
                echeance: new Date("2024-07-01"),
            },
        ],
        produitsHistorique: [
            {
                id: "PH-001",
                date: new Date("2024-01-08"),
                factureNumero: "FAC-2024-001",
                type: 'vente',
                montantTotal: 354000,
                produits: [
                    { id: "P1", reference: "BRO-001", designation: "Bière Castel 65cl (crt)", quantite: 50, prixUnitaire: 4800, total: 240000, unite: "Carton", categorie: "Boissons" },
                    { id: "P2", reference: "JUS-002", designation: "Jus Tropico 1L (crt)", quantite: 25, prixUnitaire: 2400, total: 60000, unite: "Carton", categorie: "Boissons" },
                ],
            },
            {
                id: "PH-002",
                date: new Date("2024-03-15"),
                factureNumero: "FAC-2024-015",
                type: 'vente',
                montantTotal: 590000,
                produits: [
                    { id: "P3", reference: "EAU-001", designation: "Eau Supermont 1.5L (crt)", quantite: 100, prixUnitaire: 3500, total: 350000, unite: "Carton", categorie: "Eaux" },
                    { id: "P4", reference: "BRO-001", designation: "Bière Castel 65cl (crt)", quantite: 50, prixUnitaire: 4800, total: 240000, unite: "Carton", categorie: "Boissons" },
                ],
            },
        ],
        balanceStatusData: [
            { magasin: "SURFACE VENTE ETOUDI", etat: "Facturé", blNo: "114MSVET20CP000000", livreLe: "08/01/2020", reglement: "par Compte", montantTTC: 360180 },
        ],
        paymentMethodsData: [
            { code: "CP", libelle: "par Compte", autorise: true },
            { code: "CC", libelle: "par Chèque", autorise: false },
            { code: "CE", libelle: "par Espèces", autorise: false },
        ],
        actions: [
            {
                id: "ACT-001",
                title: "Relance Facture Janvier",
                type: "RELANCE_PAIEMENT",
                object: "Facture non payée depuis 30 jours",
                followedBy: "1",
                notificationMethod: "EMAIL",
                date: new Date(new Date().setDate(new Date().getDate() + 2)),
                content: "Bonjour, sauf erreur de notre part...",
                effect: "IMMEDIATE",
                status: "PENDING",
                createdAt: new Date()
            }
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "CLI000426",
        type: "client",
        active: true,
        name: "SUPER MARCHÉ DOMINO",
        code: "CLI000426",
        pays: "CMR",
        contact: "M. TCHAPTCHET",
        formeJuridique: "SARL",
        familleClient: "Détaillant",
        segment: "REVENDEUR",
        pricingCategory: { detail: true, demisGros: false, gros: false, superGros: false },
        modesPaiementClient: ['CHEQUE', 'ESPECES'],
        categoriesVente: ['DETAIL'],
        address: "Akwa, Douala",
        city: "Douala",
        postalCode: "BP 000",
        phoneNumber: "699000000",
        email: "contact@domino.cm",
        plafondCredit: 1000000,
        financial: { solde: 150000, modesPaiementAutorises: [], devise: 'XAF' },
        factures: [
            {
                id: "FAC-010",
                numero: "FAC-2024-010",
                date: new Date("2024-02-10"),
                montantHT: 800000,
                montantTTC: 944000,
                statut: "payée",
                echeance: new Date("2024-03-10"),
            },
        ],
        produitsHistorique: [
            {
                id: "PH-010",
                date: new Date("2024-02-10"),
                factureNumero: "FAC-2024-010",
                type: 'vente',
                montantTotal: 944000,
                produits: [
                    { id: "P10", reference: "BRO-001", designation: "Bière Castel 65cl (crt)", quantite: 100, prixUnitaire: 4800, total: 480000, unite: "Carton", categorie: "Boissons" },
                    { id: "P11", reference: "SFT-003", designation: "Coca-Cola 50cl (crt)", quantite: 80, prixUnitaire: 4000, total: 320000, unite: "Carton", categorie: "Boissons" },
                ],
            },
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "CLI000427",
        type: "client",
        active: false,
        name: "LIBRAIRIE CENTRALE",
        code: "CLI000427",
        pays: "CMR",
        contact: "Mme FOUDA",
        formeJuridique: "SA",
        familleClient: "Détaillant",
        segment: "PARTICULIER",
        address: "Yaoundé Centre",
        city: "Yaoundé",
        postalCode: "BP 145",
        phoneNumber: "677123456",
        email: "librairie@centrale.cm",
        plafondCredit: 200000,
        modesPaiementClient: ['VIREMENT'],
        categoriesVente: ['DETAIL', 'DEMI_GROS'],
        financial: { solde: 0, modesPaiementAutorises: [], devise: 'XAF' },
        factures: [],
        produitsHistorique: [],
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];

export const MOCK_FOURNISSEURS: TiersFournisseur[] = [
    {
        id: "FOU000100",
        type: "fournisseur",
        active: true,
        name: "GROSSISTE KADJI",
        codeFournisseur: "FOU000100",
        pays: "CMR",
        contact: "Service Commercial",
        formeJuridique: "SA",
        familleFournisseur: "Boissons",
        address: "Zone Industrielle Bassa",
        city: "Douala",
        postalCode: "BP 456",
        phoneNumber: "677000000",
        email: "commandes@kadji.cm",
        modesPaiementFournisseur: ['VIREMENT', 'CHEQUE'],
        categoriesAchat: ['GROS', 'SUPER_GROS'],
        conditionsPaiement: "30 jours fin de mois",
        delaiLivraison: "48h",
        certification: "ISO 9001",
        financial: { solde: 0, modesPaiementAutorises: [], devise: 'XAF' },
        factures: [
            {
                id: "FFAC-001",
                numero: "FFAC-2024-101",
                date: new Date("2024-01-20"),
                montantHT: 2000000,
                montantTTC: 2360000,
                statut: "payée",
                echeance: new Date("2024-02-20"),
            },
            {
                id: "FFAC-002",
                numero: "FFAC-2024-210",
                date: new Date("2024-04-10"),
                montantHT: 3500000,
                montantTTC: 4130000,
                statut: "en retard",
                echeance: new Date("2024-05-10"),
            },
        ],
        produitsHistorique: [
            {
                id: "FPH-001",
                date: new Date("2024-01-20"),
                factureNumero: "FFAC-2024-101",
                type: 'achat',
                montantTotal: 2360000,
                produits: [
                    { id: "FP1", reference: "BRO-001", designation: "Bière Castel 65cl (crt)", quantite: 300, prixUnitaire: 4200, remise: 5, total: 1197000, unite: "Carton", categorie: "Boissons" },
                    { id: "FP2", reference: "BRO-002", designation: "33 Export 65cl (crt)", quantite: 250, prixUnitaire: 4500, total: 1125000, unite: "Carton", categorie: "Boissons" },
                ],
            },
        ],
        actions: [
            {
                id: "ACT-F01",
                title: "Négociation tarifs Q2",
                type: "DEMANDE_DEVIS",
                object: "Révision des tarifs grossiste",
                followedBy: "1",
                notificationMethod: "EMAIL",
                date: new Date(new Date().setDate(new Date().getDate() + 5)),
                content: "Demande de révision tarifaire pour le prochain trimestre",
                effect: "DEFERRED",
                status: "PENDING",
                createdAt: new Date()
            }
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "FOU000101",
        type: "fournisseur",
        active: true,
        name: "SABC - BRASSERIES",
        code: "FOU000101",
        pays: "CMR",
        contact: "Direction Commerciale",
        formeJuridique: "SA",
        familleFournisseur: "Boissons",
        modePaiement: "VIREMENT",
        modesPaiementFournisseur: ['VIREMENT'],
        categoriesAchat: ['GROS', 'SUPER_GROS'],
        conditionsPaiement: "60 jours date facture",
        delaiLivraison: "24h",
        address: "Bassa, Douala",
        city: "Douala",
        postalCode: "BP 900",
        phoneNumber: "233400000",
        email: "commercial@sabc.cm",
        financial: { solde: 0, modesPaiementAutorises: [], devise: 'XAF' },
        factures: [
            {
                id: "FFAC-010",
                numero: "FFAC-2024-010",
                date: new Date("2024-03-01"),
                montantHT: 5000000,
                montantTTC: 5900000,
                statut: "envoée",
                echeance: new Date("2024-05-01"),
            },
        ],
        produitsHistorique: [
            {
                id: "FPH-010",
                date: new Date("2024-03-01"),
                factureNumero: "FFAC-2024-010",
                type: 'achat',
                montantTotal: 5900000,
                produits: [
                    { id: "FP10", reference: "SABC-001", designation: "33 Export 65cl (crt)", quantite: 500, prixUnitaire: 5000, total: 2500000, unite: "Carton", categorie: "Boissons" },
                    { id: "FP11", reference: "SABC-002", designation: "Coca-Cola 50cl (crt)", quantite: 600, prixUnitaire: 3500, total: 2100000, unite: "Carton", categorie: "Boissons" },
                ],
            },
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];

export const MOCK_COMMERCIAUX: TiersCommercial[] = [
    {
        id: "COM001",
        type: "commercial",
        active: true,
        name: "JEAN-PAUL TCHOUA",
        code: "COM001",
        matricule: "M-2024-001",
        contact: "Jean-Paul",
        email: "jp.tchoua@comops.com",
        phoneNumber: "699998877",
        address: "Akwa",
        city: "Douala",
        postalCode: "BP 000",
        commission: 5.0,
        typeCommercial: "INTERNE",
        zonesCouvertes: "OUEST",
        clients: ["CLI000425"],
        affaires: [
            { id: "AFF1", titre: "Contrat Grossiste K", montant: 5000000, status: "gagnée", date: new Date("2024-01-15") }
        ],
        paiements: [
            { id: 'PAY-01', date: new Date('2024-01-30'), montant: 17700, reference: 'VIR-001', statut: 'payé' }
        ],
        commissionFactures: [
            {
                id: "CF-001",
                factureId: "FAC-001",
                factureNumero: "FAC-2024-001",
                clientId: "CLI000425",
                clientNom: "ABBA ABAKAR",
                dateFact: new Date("2024-01-08"),
                montantFacture: 354000,
                tauxCommission: 5,
                montantCommission: 17700,
                statut: "payé",
                datePaiement: new Date("2024-01-30"),
            },
            {
                id: "CF-002",
                factureId: "FAC-002",
                factureNumero: "FAC-2024-015",
                clientId: "CLI000425",
                clientNom: "ABBA ABAKAR",
                dateFact: new Date("2024-03-15"),
                montantFacture: 590000,
                tauxCommission: 5,
                montantCommission: 29500,
                statut: "en_attente",
                actionSuivi: { type: "RELANCE_PAIEMENT", date: new Date("2024-04-20"), note: "Relance commission mars", statut: "PENDING" },
            },
            {
                id: "CF-003",
                factureId: "FAC-003",
                factureNumero: "FAC-2024-042",
                clientId: "CLI000425",
                clientNom: "ABBA ABAKAR",
                dateFact: new Date("2024-06-01"),
                montantFacture: 141600,
                tauxCommission: 5,
                montantCommission: 7080,
                statut: "en_attente",
            },
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "COM002",
        type: "commercial",
        active: true,
        name: "MARIE NGUYEN",
        code: "COM002",
        matricule: "M-2024-002",
        contact: "Marie",
        email: "marie.n@comops.com",
        phoneNumber: "655443322",
        address: "Bastos",
        city: "Yaoundé",
        postalCode: "BP 101",
        commission: 7.0,
        typeCommercial: "INDEPENDANT",
        zonesCouvertes: "CENTRE",
        clients: ["CLI000426"],
        affaires: [
            { id: "AFF2", titre: "Appel d'offre Ministère", montant: 12000000, status: "en_cours", date: new Date() }
        ],
        paiements: [],
        commissionFactures: [
            {
                id: "CF-004",
                factureId: "FAC-004",
                factureNumero: "FAC-2024-058",
                clientId: "CLI000426",
                clientNom: "BRASCO TRADING",
                dateFact: new Date("2024-05-10"),
                montantFacture: 890000,
                tauxCommission: 7,
                montantCommission: 62300,
                statut: "en_attente",
            },
            {
                id: "CF-005",
                factureId: "FAC-005",
                factureNumero: "FAC-2024-071",
                clientId: "CLI000426",
                clientNom: "BRASCO TRADING",
                dateFact: new Date("2024-07-22"),
                montantFacture: 1250000,
                tauxCommission: 7,
                montantCommission: 87500,
                statut: "annulé",
            },
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];

export const MOCK_PROSPECTS: TiersProspect[] = [
    {
        id: "PRO001",
        type: "prospect",
        active: true,
        name: "PHARMACIE DE LA CÔTE",
        code: "PRO001",
        contact: "Dr. NGO",
        email: "pharma.cote@gmail.com",
        phoneNumber: "677112233",
        address: "Bonanjo",
        city: "Douala",
        postalCode: "BP 900",
        potentiel: "ELEVE",
        sourceProspect: "RECOMMANDATION",
        probabilite: 70,
        createdAt: new Date(),
        updatedAt: new Date(),
        notes: "Intéressé par le module stock"
    },
    {
        id: "PRO002",
        type: "prospect",
        active: true,
        name: "CLINIQUE DE L'ESPOIR",
        code: "PRO002",
        contact: "Dr. KOUAM",
        email: "contact@clinique-espoir.cm",
        phoneNumber: "699887766",
        address: "Biyem-Assi",
        city: "Yaoundé",
        postalCode: "BP 300",
        potentiel: "MOYEN",
        sourceProspect: "SITE_WEB",
        probabilite: 40,
        createdAt: new Date(),
        updatedAt: new Date(),
        notes: "A relancer semaine prochaine"
    },
    {
        id: "PRO003",
        type: "prospect",
        active: true,
        name: "BOUTIQUE MAMA SARA",
        code: "PRO003",
        contact: "Mme Sara",
        email: "",
        phoneNumber: "655001122",
        address: "Marché Central",
        city: "Douala",
        postalCode: "",
        potentiel: "FAIBLE",
        sourceProspect: "SALON",
        probabilite: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
        notes: "Petit budget, à voir"
    }
];

export const MOCK_TIERS: Tier[] = [
    ...MOCK_CLIENTS,
    ...MOCK_FOURNISSEURS,
    ...MOCK_COMMERCIAUX,
    ...MOCK_PROSPECTS
];
