export type TiersBaseDTO = {
    readonly id?: string;
    readonly accountingAccount?: string;
    bankAccountNumber?: string;
    code?: string;
    name?: string;
    shortName?: string;
    longName?: string;
    active?: boolean;
    description?: string;
    email?: string;
    phoneNumber?: string;
    website?: string;
    address?: string;
    complement?: string;
    postalCode?: string;
    city?: string;
    country?: string;
    businessSector?: string;
    companySize?: string;
    dateCreation?: string;
    tradeRegistryNumber?: string;
    taxNumber?: string;
    preferredChannel?: string;
    typeEntreprise?: string;
    tenantId?: string;
    agencyId?: string;
    createdAt?: string;
    updatedAt?: string;
    nui?: string;
    type?: string;
};
