spring.application.name=comops-core-api

# Server
server.port=8080

# URL pour l'application (R2DBC)
# URL pour l'application (R2DBC)
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yowyob}
spring.r2dbc.username=${DB_USERNAME:yowyob_user}
spring.r2dbc.password=${DB_PASSWORD}
spring.r2dbc.pool.initial-size=2
spring.r2dbc.pool.max-size=5

# Database (JDBC for Liquibase Migration)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yowyob}
spring.datasource.username=${DB_USERNAME:yowyob_user}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.user=${DB_USERNAME:yowyob_user}
spring.liquibase.password=${DB_PASSWORD}
spring.liquibase.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yowyob}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Redis (Cache)
spring.data.redis.host=${REDIS_URL}

# Logging
logging.level.org.springframework.r2dbc=INFO
logging.level.yowyob.comops=DEBUG

# JWT Security (Example secret, should be env var in prod)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400

# Jackson format configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# Swagger UI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=true