spring.application.name=comops-core-api

# Server
server.port=8080

# Database (R2DBC for Application)
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/comops_core
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20

# Database (JDBC for Liquibase Migration)
spring.datasource.url=jdbc:postgresql://localhost:5432/comops_core
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.enabled=false
spring.liquibase.user=postgres
spring.liquibase.password=postgres
spring.liquibase.url=jdbc:postgresql://localhost:5432/comops_core
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Redis (Cache)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logging
logging.level.org.springframework.r2dbc=INFO
logging.level.yowyob.comops=DEBUG

# JWT Security (Example secret, should be env var in prod)
app.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
app.jwt.expiration=86400

# Jackson format configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# Swagger UI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=true